// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTimeTracker.Entities;

namespace TaskTimeTracker.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190519121134_testdata")]
    partial class testdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTimeTracker.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("Finished");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("UserID");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tempore et quasi quo. Ut et dolor nam molestiae est. Facilis impedit consequatur accusantium dolore sunt.",
                            Finished = false,
                            Name = "kölotzeikrug.de"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Distinctio omnis soluta praesentium autem sint expedita fugiat tempora. Nulla velit ratione et est omnis illo voluptas architecto. Similique natus ipsa voluptatum id iure dolore et molestiae. Pariatur et sapiente ut ipsum mollitia quis voluptatem. Placeat voluptatem illum et aut eos mollitia debitis.",
                            Finished = false,
                            Name = "gratzky.com"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sit voluptatem aspernatur quo velit est doloribus nam facere. Velit maiores non qui repudiandae et. Atque et non voluptas. Facere enim ut laborum eos molestias et. Saepe laborum asperiores nam itaque ut et rerum vitae.",
                            Finished = false,
                            Name = "ummingerlienshöft.info"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Qui facilis eos delectus illum accusamus quae exercitationem. Quidem ea excepturi repellendus rem. Culpa voluptatum et assumenda excepturi quibusdam asperiores. Sint rerum iste neque in voluptatum porro.",
                            Finished = false,
                            Name = "schwennenbrehmer.net"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Repellat perspiciatis voluptatibus aut voluptas ipsam nam accusantium non. Veniam voluptate dolores nulla sit numquam. Eveniet doloremque dolorem explicabo fuga sit quaerat nihil. Illum est iure ullam ipsum corporis ab.",
                            Finished = false,
                            Name = "busse.net"
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.ProjectUser", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ProjectId");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("EstimatedHours");

                    b.Property<bool>("Finished");

                    b.Property<int?>("ProjectID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("ToFinish");

                    b.Property<int?>("UserID");

                    b.Property<int?>("WorkingHours");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            EstimatedHours = 12,
                            Finished = false,
                            ProjectID = 3,
                            Title = "Title1",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 332, DateTimeKind.Local).AddTicks(7197),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            EstimatedHours = 12,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title2",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4393),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            EstimatedHours = 18,
                            Finished = false,
                            Title = "Title3",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4491),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            EstimatedHours = 17,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title4",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4555),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description5",
                            EstimatedHours = 13,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title5",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4650),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description6",
                            EstimatedHours = 13,
                            Finished = false,
                            Title = "Title6",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4718),
                            UserID = 19,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description7",
                            EstimatedHours = 10,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title7",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4786),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description8",
                            EstimatedHours = 7,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title8",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4850),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description9",
                            EstimatedHours = 10,
                            Finished = false,
                            Title = "Title9",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(4918),
                            UserID = 19,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description10",
                            EstimatedHours = 19,
                            Finished = false,
                            Title = "Title10",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5133),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description11",
                            EstimatedHours = 10,
                            Finished = false,
                            Title = "Title11",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5205),
                            UserID = 14,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description12",
                            EstimatedHours = 6,
                            Finished = false,
                            Title = "Title12",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5273),
                            UserID = 8,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description13",
                            EstimatedHours = 15,
                            Finished = false,
                            ProjectID = 3,
                            Title = "Title13",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5337),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description14",
                            EstimatedHours = 18,
                            Finished = false,
                            Title = "Title14",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5405),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description15",
                            EstimatedHours = 12,
                            Finished = false,
                            Title = "Title15",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5481),
                            UserID = 2,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description16",
                            EstimatedHours = 8,
                            Finished = false,
                            ProjectID = 3,
                            Title = "Title16",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5545),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description17",
                            EstimatedHours = 1,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title17",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5613),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description18",
                            EstimatedHours = 7,
                            Finished = false,
                            Title = "Title18",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5677),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description19",
                            EstimatedHours = 9,
                            Finished = false,
                            Title = "Title19",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5749),
                            UserID = 9,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description20",
                            EstimatedHours = 9,
                            Finished = false,
                            Title = "Title20",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5824),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description21",
                            EstimatedHours = 12,
                            Finished = false,
                            ProjectID = 1,
                            Title = "Title21",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5888),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description22",
                            EstimatedHours = 17,
                            Finished = false,
                            Title = "Title22",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(5956),
                            UserID = 12,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description23",
                            EstimatedHours = 8,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title23",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6020),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description24",
                            EstimatedHours = 10,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title24",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6085),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description25",
                            EstimatedHours = 14,
                            Finished = false,
                            Title = "Title25",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6156),
                            UserID = 12,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description26",
                            EstimatedHours = 8,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title26",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6224),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description27",
                            EstimatedHours = 4,
                            Finished = false,
                            Title = "Title27",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6289),
                            UserID = 1,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description28",
                            EstimatedHours = 10,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title28",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6353),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description29",
                            EstimatedHours = 2,
                            Finished = false,
                            Title = "Title29",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6417),
                            UserID = 5,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description30",
                            EstimatedHours = 13,
                            Finished = false,
                            ProjectID = 4,
                            Title = "Title30",
                            ToFinish = new DateTime(2019, 6, 18, 14, 11, 34, 333, DateTimeKind.Local).AddTicks(6492),
                            WorkingHours = 0
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Level");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 292, DateTimeKind.Local).AddTicks(1656),
                            Email = "logan@barylla.org",
                            Firstname = "Marleen",
                            Lastname = "Frantz",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 293, DateTimeKind.Local).AddTicks(5472),
                            Email = "lindsay@hirt.de",
                            Firstname = "Friedrich",
                            Lastname = "Hess",
                            Level = 4,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 295, DateTimeKind.Local).AddTicks(80),
                            Email = "joanna.muckenthaler@strutzgeisler.de",
                            Firstname = "Henrike",
                            Lastname = "Beutelspacher",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 295, DateTimeKind.Local).AddTicks(5015),
                            Email = "martha@metzger.com",
                            Firstname = "Juna",
                            Lastname = "Byrd",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 296, DateTimeKind.Local).AddTicks(1373),
                            Email = "joris_kustermann@illing.info",
                            Firstname = "Max",
                            Lastname = "Tiedtke",
                            Level = 3,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 296, DateTimeKind.Local).AddTicks(8498),
                            Email = "karl.wanner@tonnporth.info",
                            Firstname = "Aliya",
                            Lastname = "Balck",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 297, DateTimeKind.Local).AddTicks(3045),
                            Email = "niclas.dienel@rieger.net",
                            Firstname = "Elea",
                            Lastname = "Herzenberg",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 297, DateTimeKind.Local).AddTicks(9385),
                            Email = "len_storp@lindenmayer.ch",
                            Firstname = "Patricia",
                            Lastname = "Klemme",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 298, DateTimeKind.Local).AddTicks(3885),
                            Email = "stina_decker@weber.org",
                            Firstname = "Marten",
                            Lastname = "Reus",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 298, DateTimeKind.Local).AddTicks(8204),
                            Email = "tyron@urhigblum.info",
                            Firstname = "Louis",
                            Lastname = "Konieczny",
                            Level = 4,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 299, DateTimeKind.Local).AddTicks(2747),
                            Email = "darius@sussmanngreithanner.org",
                            Firstname = "Dario",
                            Lastname = "Kurrat",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 299, DateTimeKind.Local).AddTicks(6134),
                            Email = "eleni@kempe.net",
                            Firstname = "Furkan",
                            Lastname = "Franta",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 300, DateTimeKind.Local).AddTicks(465),
                            Email = "annabell_göckeritz@krämer.info",
                            Firstname = "Eileen",
                            Lastname = "Mebold",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 300, DateTimeKind.Local).AddTicks(7053),
                            Email = "mathilde.eplinius@mertens.de",
                            Firstname = "Mats",
                            Lastname = "Möldner",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 301, DateTimeKind.Local).AddTicks(459),
                            Email = "ryan@poser.com",
                            Firstname = "Till",
                            Lastname = "Siebel",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 301, DateTimeKind.Local).AddTicks(3877),
                            Email = "celia@lipske.de",
                            Firstname = "Amon",
                            Lastname = "Roth",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 301, DateTimeKind.Local).AddTicks(9438),
                            Email = "karl@leiteritz.info",
                            Firstname = "Victoria",
                            Lastname = "Brandt",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 302, DateTimeKind.Local).AddTicks(4055),
                            Email = "jasmine_rhoden@restorff.ch",
                            Firstname = "Christin",
                            Lastname = "Bogenrieder",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 302, DateTimeKind.Local).AddTicks(7578),
                            Email = "chayenne@strohschank.info",
                            Firstname = "Lola",
                            Lastname = "Kelm",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 11, 34, 303, DateTimeKind.Local).AddTicks(4213),
                            Email = "ina_rädler@friess.info",
                            Firstname = "Evelyn",
                            Lastname = "Allgeyer",
                            Level = 4,
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.ProjectUser", b =>
                {
                    b.HasOne("TaskTimeTracker.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskTimeTracker.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.Todo", b =>
                {
                    b.HasOne("TaskTimeTracker.Entities.Project", "Project")
                        .WithMany("Todos")
                        .HasForeignKey("ProjectID");

                    b.HasOne("TaskTimeTracker.Entities.User", "User")
                        .WithMany("ToDos")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
