// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTimeTracker.Entities;

namespace TaskTimeTracker.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190519121614_testdata1")]
    partial class testdata1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTimeTracker.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("Finished");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("UserID");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Necessitatibus aut quod earum. Officia culpa voluptas totam expedita sequi et. Occaecati impedit perspiciatis culpa ratione est ut est.",
                            Finished = false,
                            Name = "gabler.ch"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Et consequatur perspiciatis atque impedit et non. Dolores voluptatem consequatur quod nam molestiae dolore magni quo. Mollitia harum et et est facilis id quis id.",
                            Finished = false,
                            Name = "kern.org"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Asperiores omnis a et ipsum dignissimos. Aut distinctio sunt iure sunt voluptate voluptatibus laborum. Aut nihil vel explicabo id est.",
                            Finished = false,
                            Name = "stregepöge.com"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blanditiis maiores ducimus quia voluptas consequatur tempore ratione quis. Sed qui autem placeat labore. Sit et consectetur nemo sed aut doloribus voluptatibus non. Voluptas ullam rem officiis.",
                            Finished = false,
                            Name = "brettschneider.ch"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sed quaerat aut aperiam nemo laudantium et libero. Ea corporis at dignissimos. Placeat eum est odit assumenda laboriosam. Totam repudiandae dolorum id consequatur cum esse amet dolore.",
                            Finished = false,
                            Name = "hackelbusch.ch"
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.ProjectUser", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ProjectId");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("EstimatedHours");

                    b.Property<bool>("Finished");

                    b.Property<int?>("ProjectID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("ToFinish");

                    b.Property<int?>("UserID");

                    b.Property<int?>("WorkingHours");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            EstimatedHours = 9,
                            Finished = false,
                            Title = "Title1",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4468),
                            UserID = 5,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            EstimatedHours = 17,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title2",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4694),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            EstimatedHours = 7,
                            Finished = false,
                            Title = "Title3",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4774),
                            UserID = 8,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            EstimatedHours = 11,
                            Finished = false,
                            ProjectID = 1,
                            Title = "Title4",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4838),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description5",
                            EstimatedHours = 16,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title5",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4906),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description6",
                            EstimatedHours = 2,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title6",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(4974),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description7",
                            EstimatedHours = 6,
                            Finished = false,
                            ProjectID = 1,
                            Title = "Title7",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5046),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description8",
                            EstimatedHours = 3,
                            Finished = false,
                            ProjectID = 3,
                            Title = "Title8",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5117),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description9",
                            EstimatedHours = 1,
                            Finished = false,
                            Title = "Title9",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5182),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description10",
                            EstimatedHours = 13,
                            Finished = false,
                            Title = "Title10",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5249),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description11",
                            EstimatedHours = 1,
                            Finished = false,
                            ProjectID = 1,
                            Title = "Title11",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5317),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description12",
                            EstimatedHours = 7,
                            Finished = false,
                            Title = "Title12",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5385),
                            UserID = 9,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description13",
                            EstimatedHours = 16,
                            Finished = false,
                            Title = "Title13",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5457),
                            UserID = 10,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description14",
                            EstimatedHours = 17,
                            Finished = false,
                            Title = "Title14",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5521),
                            UserID = 4,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description15",
                            EstimatedHours = 16,
                            Finished = false,
                            Title = "Title15",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5586),
                            UserID = 1,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description16",
                            EstimatedHours = 18,
                            Finished = false,
                            Title = "Title16",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5653),
                            UserID = 1,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description17",
                            EstimatedHours = 17,
                            Finished = false,
                            ProjectID = 4,
                            Title = "Title17",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5718),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description18",
                            EstimatedHours = 2,
                            Finished = false,
                            ProjectID = 4,
                            Title = "Title18",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5789),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description19",
                            EstimatedHours = 3,
                            Finished = false,
                            Title = "Title19",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5857),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description20",
                            EstimatedHours = 4,
                            Finished = false,
                            Title = "Title20",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5922),
                            UserID = 15,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description21",
                            EstimatedHours = 12,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title21",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(5986),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description22",
                            EstimatedHours = 18,
                            Finished = false,
                            Title = "Title22",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6054),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description23",
                            EstimatedHours = 3,
                            Finished = false,
                            Title = "Title23",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6125),
                            UserID = 15,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description24",
                            EstimatedHours = 2,
                            Finished = false,
                            ProjectID = 1,
                            Title = "Title24",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6193),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description25",
                            EstimatedHours = 14,
                            Finished = false,
                            Title = "Title25",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6258),
                            UserID = 10,
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description26",
                            EstimatedHours = 13,
                            Finished = false,
                            ProjectID = 5,
                            Title = "Title26",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6322),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description27",
                            EstimatedHours = 7,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title27",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6386),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description28",
                            EstimatedHours = 4,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title28",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6462),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description29",
                            EstimatedHours = 9,
                            Finished = false,
                            ProjectID = 2,
                            Title = "Title29",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6529),
                            WorkingHours = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description30",
                            EstimatedHours = 18,
                            Finished = false,
                            Title = "Title30",
                            ToFinish = new DateTime(2019, 6, 18, 14, 16, 13, 902, DateTimeKind.Local).AddTicks(6594),
                            WorkingHours = 0
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Level");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 866, DateTimeKind.Local).AddTicks(2364),
                            Email = "josua@bönisch.info",
                            Firstname = "Tamino",
                            Lastname = "Huth",
                            Level = 4,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 868, DateTimeKind.Local).AddTicks(2422),
                            Email = "cedric_thieke@bayer.net",
                            Firstname = "Jari",
                            Lastname = "Loska",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 868, DateTimeKind.Local).AddTicks(8319),
                            Email = "hamza@sürth.name",
                            Firstname = "Juna",
                            Lastname = "Kempter",
                            Level = 4,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 869, DateTimeKind.Local).AddTicks(5681),
                            Email = "lotte@goldfusswühn.net",
                            Firstname = "Kim",
                            Lastname = "Dietz",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 870, DateTimeKind.Local).AddTicks(329),
                            Email = "elena.hillard@kochan.net",
                            Firstname = "Alena",
                            Lastname = "Sladek",
                            Level = 3,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 870, DateTimeKind.Local).AddTicks(6205),
                            Email = "burak@weber.name",
                            Firstname = "Emilia",
                            Lastname = "Leimbach",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 870, DateTimeKind.Local).AddTicks(9743),
                            Email = "steven@köhler.info",
                            Firstname = "Zeynep",
                            Lastname = "Fust",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 871, DateTimeKind.Local).AddTicks(6422),
                            Email = "bela.brandis@schwarthoff.ch",
                            Firstname = "Cara",
                            Lastname = "Beyer",
                            Level = 3,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 872, DateTimeKind.Local).AddTicks(976),
                            Email = "filip_volkmann@burkhardt.name",
                            Firstname = "Moritz",
                            Lastname = "Kofferschlager",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 872, DateTimeKind.Local).AddTicks(8112),
                            Email = "elisa_eifert@smieja.net",
                            Firstname = "Jordan",
                            Lastname = "Sujew",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 873, DateTimeKind.Local).AddTicks(4637),
                            Email = "johann@wessinghage.info",
                            Firstname = "Raul",
                            Lastname = "Neumair",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 874, DateTimeKind.Local).AddTicks(361),
                            Email = "rené.mehlorn@lichtenhagenbrunner.de",
                            Firstname = "Letizia",
                            Lastname = "Obergföll",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 874, DateTimeKind.Local).AddTicks(7433),
                            Email = "yves@blumeniklaus.com",
                            Firstname = "Giuliano",
                            Lastname = "Schmidt",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 875, DateTimeKind.Local).AddTicks(2444),
                            Email = "angelina_könig@roloff.com",
                            Firstname = "Jule",
                            Lastname = "Erdmann",
                            Level = 3,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 880, DateTimeKind.Local).AddTicks(4947),
                            Email = "elia_sokolowski@stepanov.info",
                            Firstname = "Emilie",
                            Lastname = "Onnen",
                            Level = 4,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 880, DateTimeKind.Local).AddTicks(8972),
                            Email = "laurin_herschmann@lange.org",
                            Firstname = "Ilja",
                            Lastname = "Riediger",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 881, DateTimeKind.Local).AddTicks(2253),
                            Email = "kerem_schwarzkopf@sewaldgruber.ch",
                            Firstname = "Elisa",
                            Lastname = "Mockenhaupt",
                            Level = 3,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 881, DateTimeKind.Local).AddTicks(6206),
                            Email = "boris_nagel@schielke.com",
                            Firstname = "Angelique",
                            Lastname = "Köpernick",
                            Level = 1,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 881, DateTimeKind.Local).AddTicks(9494),
                            Email = "francesca@arendt.ch",
                            Firstname = "Darian",
                            Lastname = "Schimmer",
                            Level = 5,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 882, DateTimeKind.Local).AddTicks(2485),
                            Email = "andre_hübner@bauer.net",
                            Firstname = "Milo",
                            Lastname = "Gottschalk",
                            Level = 2,
                            Password = "1234"
                        },
                        new
                        {
                            Id = 777,
                            Active = true,
                            Created = new DateTime(2019, 5, 19, 14, 16, 13, 882, DateTimeKind.Local).AddTicks(2609),
                            Email = "k@s.eu",
                            Firstname = "Kelvin",
                            Lastname = "Sparr",
                            Level = 0,
                            Password = "password"
                        });
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.ProjectUser", b =>
                {
                    b.HasOne("TaskTimeTracker.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskTimeTracker.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskTimeTracker.Entities.Todo", b =>
                {
                    b.HasOne("TaskTimeTracker.Entities.Project", "Project")
                        .WithMany("Todos")
                        .HasForeignKey("ProjectID");

                    b.HasOne("TaskTimeTracker.Entities.User", "User")
                        .WithMany("ToDos")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
